# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05250b37e8a7810fbabf70a90162d40af7479e30050f08852ba66355fc7353f6e132382a212d76a61da1d4ab1f002c2583f8a70a45fba3540534f01eecf0ca0f

test:
  secret_key_base: e98e9dba83112b690109687358cdb82de164a31f13435a7b437b73562c3767b15b2711b5f2871e40ab5b1353046970bcadc19c54723228173bd28c2b3feb3dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
